version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app                  
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
    - .env

  db:
    image: postgres:16
    container_name: finance-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: golf
      POSTGRES_PASSWORD: golf123

  frontend:
    build:
      context: ./finance-tracker    # React frontend folder
      dockerfile: Dockerfile
    container_name: finance-frontend
    volumes:
      - frontend_build:/usr/share/nginx/html
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  frontend_build:
