# Generated by Django 5.1.6 on 2025-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
