# Generated by Django 5.1.6 on 2025-03-17 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_created_at_transaction_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('water', 'Water'), ('rent', 'Rent'), ('electricity', 'Electricity'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('bill_payment', 'Bill Payment'), ('income', 'Income'), ('expense', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
